// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vatsal278/UserManagementService/internal/handler (interfaces: UserManagementServiceHandler)

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserManagementServiceHandler is a mock of UserManagementServiceHandler interface.
type MockUserManagementServiceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockUserManagementServiceHandlerMockRecorder
}

// MockUserManagementServiceHandlerMockRecorder is the mock recorder for MockUserManagementServiceHandler.
type MockUserManagementServiceHandlerMockRecorder struct {
	mock *MockUserManagementServiceHandler
}

// NewMockUserManagementServiceHandler creates a new mock instance.
func NewMockUserManagementServiceHandler(ctrl *gomock.Controller) *MockUserManagementServiceHandler {
	mock := &MockUserManagementServiceHandler{ctrl: ctrl}
	mock.recorder = &MockUserManagementServiceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserManagementServiceHandler) EXPECT() *MockUserManagementServiceHandlerMockRecorder {
	return m.recorder
}

// HealthCheck mocks base method.
func (m *MockUserManagementServiceHandler) HealthCheck() (string, string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockUserManagementServiceHandlerMockRecorder) HealthCheck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockUserManagementServiceHandler)(nil).HealthCheck))
}

// Ping mocks base method.
func (m *MockUserManagementServiceHandler) Ping(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Ping", arg0, arg1)
}

// Ping indicates an expected call of Ping.
func (mr *MockUserManagementServiceHandlerMockRecorder) Ping(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockUserManagementServiceHandler)(nil).Ping), arg0, arg1)
}
